apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yml
  - https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.4/manifests/quick-start-postgres.yaml
  # - https://github.com/argoproj/argo-workflows/releases/download/v3.4.4/install.yaml

patchesStrategicMerge:
  - config.yml

helmCharts:
  - name: minio
    includeCRDs: true
    # version: 1.16.1
    repo: https://helm.min.io/
    releaseName: argo-artifacts
    namespace: argo
    valuesInline:
      service:
        type: LoadBalancer
      defaultBucket:
        enabled: true
        name: artifacts
      persistence:
        enabled: false
      fullnameOverride: argo-artifacts
